### ISSUE TITLE
Add pre-commit to Github Actions

### ISSUE THREAD

**Issue by pythoninja** [randomicu/fakedata-provider#158]
Action: https://github.com/pre-commit/action

Job example:
```
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.4
    - uses: pre-commit/action@v2.0.3
```
